server:
  port: 8081
grpc:
  client:
    peopleService:
        address: "static://localhost:9090"
        enable-keep-alive: true
        keep-alive-without-calls: true
        negotiation-type: plaintext
